#/bin/bash
echo "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMMWX0KNWWXkkKXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMXkc;:dddl;;:xKNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMNOc;;;;:;;;:xKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMNKOo;;lk00Oxc;:loxKWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMNx;;;;:OXXNWNx;;;;cOXXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMWOllc;;oOKXXOl;;okOKXNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMWWN0l;;:ccc;;;lOKK0OkkKWWWMWKkO0XNWMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMMXo;;;cclc;;ckOd:;;;o0KKX0l;;;:xKNNWMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMMN0xod0K0Oxx0K0o;;;;;cccc:;;;;;d0XXWMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMMMMMWN0xlldOOol:;;;;;;;;;;;;;;;:cokKNWMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMMMMMNOo;;;;;;;;;;;;;;;;;;;;;;;;;;;;cxKNWMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMMMMMMXkc;;;;;;;;;;;;;:cccc:;;;;;;;:oOKXXWMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMMMMMMW0l;;;;;;;;;cdkO0KKKKK0xoc;;lkKXNNWMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMWKOOOkl;;;;;;;:okKXNNWWMMMMMMWXO0KXNNWMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMKd;;;;;;;;;;;ckKXXNWMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMWOl;;;;;;;;;;:kKXXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMNXOd:;;;;;;;o0XXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMMMW0c;;;;;;;o0XXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMMWXkc;;;;;;;o0XXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMW0oc;;;;;;;;;:kKXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMKo;;;;;;;;;;;:kKXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMNkoooo:;;;;;;;:oOKNWMMMMMMMMMWNKKNWMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMMWWWNXkc;;;;;;;;:ldkOKXXXXK0kdc::oOKNWMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMMMMMMW0l;;;;;;;;;;;;;;::::;;;;;;;;:oOXNWMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMMMMMW0l;;;;;;;;;;;;;;;;;;;;;;;;;;;;cxKXNWMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMMMMMMNOl::lddl:;;;;;;;;;;;;;;;;;cox0XXNWMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMMMMWNWWX0OOKKX0o;;;;;;:::;;;;;;d0KXNNWMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMMN0dld000dccd00o;;;;ck000kc;;;;xKXXWMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMMKo;;;:;;;;;lOKOxdooOKXNWNOoodx0XXNWMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMWXd;;:lddl:;:oO0KNNNNNNWMMWNWNNWWWWMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMNOdo:;ckKXXX0l;;::oKNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMXd;;;;lOXXWMKo;;:cd0XXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMWKOkl;;cdkkxl;;lOKXXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMMMKl;;;;;;;;;o0XXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMMW0oc:lkOOdclx0XXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMMMMNXKKNNNNXNNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"


HTTP_DIR=$CRAFTER_DEPLOYER_HOME/target/site/content/
DEPLOYER_FILE=$CRAFTER_DEPLOYER_HOME/conf/site-target-context.xml

if [ ! -d "$HTTP_DIR" ]; then
  if [ ! -L "$HTTP_DIR" ]; then
    # It is a symlink!
    # Symbolic link specific commands go here.
     mkdir -pv $HTTP_DIR
  else
    # dir
     mkdir -pv $HTTP_DIR
  fi
fi

if [ ! -f "$DEPLOYER_FILE" ]; then
  if [ ! -L "$DEPLOYER_FILE" ]; then
    # It is a symlink!
    # Symbolic link specific commands go here.
    cp $TMP_PATH/site-target-context.xml $CRAFTER_DEPLOYER_HOME/conf/
  else
    # dir
     cp $TMP_PATH/site-target-context.xml $CRAFTER_DEPLOYER_HOME/conf/
  fi
fi

exec supervisord -c /etc/supervisor/supervisord.conf
